### ISSUE TITLE
Updated LTS Kernel

### ISSUE THREAD

**Issue by abhi-deshpande** [chrultrabook/debian-kernel#2]
I have compiled updated kernel (6.6.xx LTS) in my fork. Tested on MX Linux 23 and working fine. Check it [here.](https://github.com/abhi-deshpande/debian-kernel/releases/)

**Comment by WeirdTreeThing** [comment]
This repo has now been updated

**Comment by abhi-deshpande** [comment]
Thank You..!

**Comment by abhi-deshpande** [comment]
Closing this issue as it's no more relevant.
